# Generated by Django 5.0.3 on 2024-03-30 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('two_f_auth', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='sms_otp',
            new_name='mail_otp',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='otp_base32',
            new_name='qr_otp',
        ),
        migrations.RemoveField(
            model_name='user',
            name='logged_in',
        ),
    ]
